server:
  port: 8080
  servlet.contextPath: /bbs

spring.datasource:
  url: jdbc:mysql://106.14.149.8:3306/bbs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  jmx:
    default-domain: bbs


  #Elasticsearch
  #spring.data.elasticsearch.cluster-nodes=127.0.0.1:9300

  #Elasticsearch bbs索引地址  使用ES的web restful接口方式 让BBS项目与ES解耦

elasticsearch.bbs:
  url: http://127.0.0.1:9200/bbs
  content-url: http://127.0.0.1:9200/bbs/content/
  content-search-url: http://127.0.0.1:9200/bbs/content/_search

beetl.suffix: html
beetl-beetlsql.dev: true
beetlsql:
  mutiple.datasource: dataSource
  ds.dataSource.basePackage: com.ibeetl.bbs.dao


bbs.user:
  register-same-ipL: 1 # 同一个IP一天只允许注册用户个数
  topic-count: 2  # 同一个用户规定时间内只能发一个帖子
  topic-count-minutes: 120

